### ISSUE TITLE
Tooltip is not taking scroll to account

### ISSUE THREAD

**Issue by nighto** [MinisterioPublicoRJ/inLoco-2.0#172] opened 2017-07-05 19:56 UTC
![image](https://user-images.githubusercontent.com/397851/27882381-d5204212-61a2-11e7-832b-a6b576304ebb.png)

Notice the scroll bar. When mouse highlights an element, the tooltip is at wrong position.

**Comment by rlage** [comment] 2017-07-07 17:40
@nighto the issue happens when the scroll top is not matching a layer top. It happens when there is a mix o categories and viewport size that makes scrollTop 0 not matching a layer. Sometimes it is one pixel of difference, it is almost impossible to see. The image below shows it. You can see a little line at the top, this is the 1px difference. When there is no line, so the top of the layer is aligned to scrollTop 0, the problem does not happen.

![tooltip-bug](https://user-images.githubusercontent.com/1390422/27969672-20f00828-6322-11e7-8f62-c7adebe7127c.png)

**Comment by rlage** [comment] 2017-07-07 19:49
Adding more info about the problem: 
When the scroll value is, for instanse 53, which is not divisible by 33, we divide it by 33, then we round the result and multiply by 33, so the rounded scroll value is 66, which is divisible by 33. This means that when the user scrolls and the view port top is in the middle of a layer (not on top), it pulls up or pushes it down, so that the viewport top matches a top layer. When it goes down, i.e, the next layer goes to the top of the viewport, like the example, from 53 to 66. The problem is, when it reaches the end of the list, because there is nowhere to scroll, so it stays at 53, regardless of what we assign to scrollTop value. In other words, it is impossible to go to 66. That messes the calculation for the tooltip.

**Comment by nighto** [comment] 2017-07-10 15:29
Maybe the solution would be to simply add an empty element (or, rather, add a >33px margin on the bottom)? We should try that.

**Closed** 2017-07-12 18:20 UTC
Labels: prio: medium, type: bug
